@startuml

entity "U1" as u1
entity "G1" as g1
entity "U2" as u2
entity "G2" as g2

u1->g1: [1]: transfer X amount of asset Y to U2
g1->u1: [2]: transfer is ok. Proceed?
u1->g1: [3]: ok

g1->g2: [4] initiate ODAP session
g2->g1: [5] ok

g1->g2: [6] start transfer initation flow
g2->g2: [7] validity checks
g2->g1: [8] ok

g1->g2: [9] start lock-evidence \n verification flow
g2->g1: [10] ok

g1->g1: [11] lock X amount of asset Y
g1->g2: [12] send proof

g2->g2: [13] store proof. \n validate proof
g2->g1: [14] transfer ok.

g1->g2: [15] initiate commitment \n establishment flow
g2->g1: [16] ok

g1->g2: [17] transfer finalized
g2->g1: [18] ok

@enduml